# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
<<<<<<< HEAD
- wikiMaster
=======
- draft
>>>>>>> 570dc05e73a1208f9d32192e545a0bb176f20a9c

pool:
  vmImage: 'ubuntu-latest'

steps:
<<<<<<< HEAD

<<<<<<< HEAD
=======
# instalando nodejs
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'instalando node js'
# fin nodejs

>>>>>>> 570dc05e73a1208f9d32192e545a0bb176f20a9c
- script: |
    ls -a
    mkdir ../github-docs
    mkdir ../github-docs/.attachments
    mv ./.attachments/* ../github-docs/.attachments
    mv ./* ../github-docs
    ls -a ../github-docs/
    
    
    git clone https://alejandro.iglesias:$(token)@dev.azure.com/yo-fenix/blog/_git/blog web
        
    cd web
    git checkout draft || git checkout -b draft
    mkdir static
    mkdir static/.attachments
    mkdir content
    pwd    
    cd ..
    cp -r ../github-docs/* ./web/content
    cp -r ../github-docs/.attachments/* ./web/static/.attachments

    pwd
    echo $(Build.SourcesDirectory)


  displayName: 'clone from github to wiki'


- task: replacetokens@3
  inputs:
    rootDirectory: '$(Build.SourcesDirectory)'
    targetFiles: '**/config.js'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: false

#instalando gatsby
- script: |   
    npm install -g gatsby-cli
  displayName: 'instalando gatsby'
#fin gatsby

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npm install'
    workingDirectory: '$(Build.SourcesDirectory)/web'
  displayName: 'npm install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npm install --save-dev @babel/plugin-proposal-export-default-from'
    workingDirectory: '$(Build.SourcesDirectory)/web'
  displayName: 'npm install babel'

#gatsby build
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'gatsby build'
    workingDirectory: '$(Build.SourcesDirectory)/web'
  displayName: 'gatsby build'
#fin gatsby build

#copiando archivos a salida
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/web/public'
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)
    CleanTargetFolder: true
#fin copiando archivos a salida

#publicando artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'drop'
    publishLocation: 'container'
#fin publicando artifacts
<<<<<<< HEAD
=======
>>>>>>> efae4486725fbc94fa86dd333132e6a310fb3a60



- script: |
    ls
    mkdir ../github
    cd ../github
    git config --global user.email "$(user)"
    git config --global user.name "$(email)"
    git clone https://$(user):$(token)@github.com/$(user)/wiki-uv.git
  displayName: "Paso1" 

- script: |
    cd ../github/wiki-uv
    ls -a
    git remote add upstream  https://github.com/trifenix/wiki-uv.git
    git fetch upstream
    
    git checkout --track origin/draft
    git merge upstream/draft 
  displayName: "Paso2"
- script: |
    ls
    cp -r ./* ../github/wiki-uv
    cp -r ./.attachments/* ../github/wiki-uv/.attachments
    cd ../github/wiki-uv
    ls 
    git add . && git commit -m "actualizacion documentacion"    
    git push origin draft
  displayName: "Paso3"
=======




>>>>>>> 570dc05e73a1208f9d32192e545a0bb176f20a9c
